use_frameworks!

platform :ios, '10.0'

target 'ORFramework_Example' do
  pod 'ORFramework', :path => '../'

  target 'ORFramework_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
